apiVersion: v1
kind: Pod
metadata:
  name: secret-env-example
spec:
  containers:
    - name: my-container
      image: busybox
      args: ['tail', '-f', '/dev/null']
      env:
        - name: YOUR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: our-password
              key: pw2
