apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-nginx
spec: # replicaset 정의
  replicas: 4
  selector:
    matchLabels:
      app: my-nginx-pods-label
  template: # Pod 정의
    metadata:
      name: my-nginx-pod
      labels:
        app: my-nginx-pods-label
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
        
